### ISSUE TITLE
LCD not working for me

### ISSUE THREAD

**Issue by ColPaulR** [hurzhurz/Duet-USB-CNC-Pendant#2]
Do you have the LCD printing out the correct information? I can't get mine to work.

I don't have a Duet but rather am running FluidNC on a TinyBee. I forked your repository at [GRBL-USB-CNC-Pendan](https://github.com/ColPaulR/GRBL-USB-CNC-Pendant) and have converted the Duet interface to GRBL, as well as creating an array of functions based on button press vs. the array of strings lookup that you instituted. I really appreciate your work here as that kickstarted my effort considerably.

Most everything is working, but I can't get the LCD to display my information. I have an older wired version from AliExpress, as well as a new wireless version (both 4 axis) from AliExpress. The tag on that back of the wireless has LHB04B-4 TX: v03 with what I'm assuming is a date code of 20201224.

Thanks again for providing your efforts to the community!

**Comment by hurzhurz** [comment]
I’m happy to heat that my project is useful for you 😊

For me the LCD is working fine. Maybe just keep in mind that an axis has to be selected as mentioned here:
https://github.com/LinuxCNC/linuxcnc/tree/master/src/hal/user_comps/xhc-whb04b-6#issues

I have compiled and tested your project (but without a connected CNC machine).
First thing I noticed is that the pendant directly displayed the axis letters with a “1” (X1, Y1, Z1, …). This is a indication that it receives reports, as this indicator for workspace coordinates (instead machine coordinates) is not default. Is this the case for you as well?

Other thing I tried was uncommenting my demo axis coordinates block here, which did work and showed me those pseudo coordinates: https://github.com/ColPaulR/GRBL-USB-CNC-Pendant/blob/master/src/Pendant_WHB04B6.cpp#L79

The label of my dongle is different, says “WHB04B-6 TX:V19 RX:V19”. And datecode is 20221122, so 2 years newer?
Though most of the documentation from LinuxCNC about the pendant is even older.

And from what I found out from googling, there shouldn’t be a big difference between the 4 and 6 axis versions.

**Comment by ColPaulR** [comment]
Thanks for helping me with this. I merged in some of your never code and uncommented the test coordinates as you suggested.  I switched to my newer/wirelss and this is working!!

I have both the machine and work coordinates. Do you know to have the pendant switch between the two?

**Comment by hurzhurz** [comment]
Great that it's working now!

You have to decide which coordinates you send to the pendant, it doesn't really care which it gets. But you should set the indicator accordingly.
At the moment, I have not implemented switching between both coordinate types and have hard coded the work-coordinate-indicator here:
https://github.com/ColPaulR/GRBL-USB-CNC-Pendant/blob/master/src/Pendant_WHB04B6.cpp#L60 (0x81, highest bit set to one)

You could implement the flag here:
https://github.com/ColPaulR/GRBL-USB-CNC-Pendant/blob/master/src/Pendant_WHB04B6.cpp#L177
Like this:

```
uint8_t coordinatetype_bit;
if(... work ...)
  coordinatetype_bit = (1<<7); // or 0x80
else
  coordinatetype_bit = 0;

this->display_report_data[R_IDX(3)] = (this->display_report_data[R_IDX(3)] & (~0x80)) | coordinatetype_bit;
```

**Comment by ColPaulR** [comment]
Excellent! I got the code working. GRBL has a $10 variable that reports back machine position or work position. The pendant now indicates whichever coordinate system is in use. I'll set up one of the macros to toggle the $10 variable later. I've got step move jog working (GRBL has a dedicated jog state with non-modal settings for incremental position move and/or feedrate changes). Once I confirm the STOP button works in an immediate/non-command queued way, I'll start looking at your continuous jog functions. Thanks again for all the help!

**Comment by ColPaulR** [comment]
If you are still willing to help me, I'm trying to drill down as to why the older device will not update the LCD. I adapted some code previously in NodeJS at [[cncjs-pendant-XHC](https://github.com/ColPaulR/cncjs-pendant-XHC)](https://github.com/ColPaulR/cncjs-pendant-XHC) to interface the older pendant with cncjs. I discovered that these devices are actually composite USB devices (I'm still learning what that means and how to interface with them) and that I could read the buttons from Col1 and write the LCD to Col2 when I opened each as a separate handle.

Below is the output of Windows hidapitester.exe. Notice the Col01 and Col02 in the device path.

```
X:\Downloads\hidapitester-windows-x86_64>hidapitester.exe --vidpid 10CE --list-detail -v
10CE/EB93: KTURT.LTD -
  vendorId:      0x10CE
  productId:     0xEB93
  usagePage:     0xFF00
  usage:         0x0001
  serial_number:
  interface:     0
  path: \\?\HID#VID_10CE&PID_EB93&Col01#7&2a6ce7d5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

10CE/EB93: KTURT.LTD -
  vendorId:      0x10CE
  productId:     0xEB93
  usagePage:     0xFF00
  usage:         0x0001
  serial_number:
  interface:     0
  path: \\?\HID#VID_10CE&PID_EB93&Col02#7&2a6ce7d5&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
```

Are you seeing the same composite device on your pendant and if so, do you know how to reference it?

**Comment by hurzhurz** [comment]
My pendant shows up exactly the same in hidapitester. Though I'm not sure if this indicates a composite device.
I guess a composite device is more something like the receiver dongle that acts as a keyboard and mouse.
This is the output on the serial console, generated at https://github.com/hurzhurz/Duet-USB-CNC-Pendant/blob/master/src/main1.cpp#L152-L161 :
```
HID device address = 1, instance = 0 is mounted
VID = 062a, PID = 4101
HID Interface Protocol = Keyboard(1)
...
HID device address = 1, instance = 1 is mounted
VID = 062a, PID = 4101
HID Interface Protocol = Mouse(2)
```
Two devices with the same VID/PID/(bus)address but a different instance.

The pendant looks like this:
```
HID device address = 2, instance = 0 is mounted
VID = 10ce, PID = eb93
HID Interface Protocol = None(0)
```
So, only one device / instance.
And it looks like "interface" from the hidapitester output is the same as the "instance" here.

Col01/Col02 (=USB HID Columns?) are probably something completely different.

One idea I have is that you could try some things with this line:
https://github.com/ColPaulR/GRBL-USB-CNC-Pendant/blob/master/src/Pendant_WHB04B6.cpp#L125C28-L125C51
`this->set_report(0x06, HID_REPORT_TYPE_FEATURE, &this->display_report_data, 24);`
Maybe try `HID_REPORT_TYPE_OUTPUT` or a different report_id instead of 0x06.

And maybe you can give me some examples for received HID reports and working display reports sent by cncjs-pendant-XHC.
Maybe there is anything different from my pendant...

**Comment by ColPaulR** [comment]
I've install https://freeusbanalyzer.com/ to see what was going on at the USB bus traffic level. I have some logs saved but they appear to be in the program's format vs. text readable. I'll get you the files if you are willing to use the free program.

In addition, I added some code to main1.cpp at lines 194-201 to print the description report for both devices.  Below is the report for the older wired device that isn't updating the LCD.

```6 0 FF 9 1 A1 1 85
4 9 1 15 0 26 FF 0
95 7 75 8 81 2 C0 6
0 FF 9 1 A1 1 85 6
9 1 15 0 26 FF 0 95
7 75 8 B1 6 C0
```
Using https://eleccelerator.com/usbdescreqparser/, this appears to mean two collections.
```0x06, 0x00, 0xFF,  // Usage Page (Vendor Defined 0xFF00)
0x09, 0x01,        // Usage (0x01)
0xA1, 0x01,        // Collection (Application)
0x85, 0x04,        //   Report ID (4)
0x09, 0x01,        //   Usage (0x01)
0x15, 0x00,        //   Logical Minimum (0)
0x26, 0xFF, 0x00,  //   Logical Maximum (255)
0x95, 0x07,        //   Report Count (7)
0x75, 0x08,        //   Report Size (8)
0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
0xC0,              // End Collection
0x06, 0x00, 0xFF,  // Usage Page (Vendor Defined 0xFF00)
0x09, 0x01,        // Usage (0x01)
0xA1, 0x01,        // Collection (Application)
0x85, 0x06,        //   Report ID (6)
0x09, 0x01,        //   Usage (0x01)
0x15, 0x00,        //   Logical Minimum (0)
0x26, 0xFF, 0x00,  //   Logical Maximum (255)
0x95, 0x07,        //   Report Count (7)
0x75, 0x08,        //   Report Size (8)
0xB1, 0x06,        //   Feature (Data,Var,Rel,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
0xC0,              // End Collection

// 46 bytes
```

Likewise for my newer wireless pendant that updates the LCD:
```
6 0 FF 9 1 A1 1 85
4 9 1 15 0 26 0 FF
75 8 95 7 81 2 C0 6
0 FF 9 1 A1 1 85 6
9 1 15 0 26 0 FF 75
8 95 7 B1 6 C0

0x06, 0x00, 0xFF,  // Usage Page (Vendor Defined 0xFF00)
0x09, 0x01,        // Usage (0x01)
0xA1, 0x01,        // Collection (Application)
0x85, 0x04,        //   Report ID (4)
0x09, 0x01,        //   Usage (0x01)
0x15, 0x00,        //   Logical Minimum (0)
0x26, 0x00, 0xFF,  //   Logical Maximum (-256)
0x75, 0x08,        //   Report Size (8)
0x95, 0x07,        //   Report Count (7)
0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
0xC0,              // End Collection
0x06, 0x00, 0xFF,  // Usage Page (Vendor Defined 0xFF00)
0x09, 0x01,        // Usage (0x01)
0xA1, 0x01,        // Collection (Application)
0x85, 0x06,        //   Report ID (6)
0x09, 0x01,        //   Usage (0x01)
0x15, 0x00,        //   Logical Minimum (0)
0x26, 0x00, 0xFF,  //   Logical Maximum (-256)
0x75, 0x08,        //   Report Size (8)
0x95, 0x07,        //   Report Count (7)
0xB1, 0x06,        //   Feature (Data,Var,Rel,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
0xC0,              // End Collection

// 46 bytes
```

I don't know what all this means, but that does match my Node JS code where I had to open the 2nd collection to write to the LCD. The HID device had "Col2" in the string name. If I tried to write to handle that had "Col1" in the string name, the LCD was unresponsive, just like this Pico code.

I have some homework tomorrow to better understand HID collections, but I think I need to figure out how to write to the collection 2 endpoint vs. the collection 1 endpoint to get this to work like my Node JS code.

**Comment by hurzhurz** [comment]
Well, I'm not keen on using that random software, but I'm also curious and would like to have a look at the logs.
So yeah, would be great if you could give them to me!

Ok, the descriptors are not absolutely identical. But almost.

I guess you have tested if the newer pendant model works with your Node JS code?
Can you check if it also requires Col2 or if it also works with Col1?
Because if it doesn't work with Col1, like the older one, I think we can rule that Col part out.

I have the idea that the Col selection might happen automatically on the Pico, based on the report id and report type.
The function "tuh_hid_set_report", that is used to send the report, wants both as parameters.
In the Node JS code, if I understand it right, it looks like you use a function for the report type and it doesn't get the report id as a separate parameter.
(the report id 0x06 is also in the report data in both cases, but I wouldn't count that)

**Comment by ColPaulR** [comment]
I’ll try changing the new wireless pendant to Col1 on the report and see if it ignores it. Also, my Node JS code sends 3 reports at 8 bytes each vs a single 24 byte report.  Both pendants accept the node js three 8 byte reports.  I’ll also see if node will work with a 24 byte report. 

Thanks for being willing to help me with all this.

**Comment by hurzhurz** [comment]
Yep, I think LinuxCNC also sends it in 3 packets with 8 bytes each.
Though this doesn't seem to be trivial to get it working with Adafruit TinyUSB.
One problem is that tuh_hid_set_report is not synchronous/blocking, so calling it multiple times in a row doesn't work well.
And using the delay() function in between, which helped me at another occasion when testing something else, doesn't work here, the pendant didn't interpret the 2. and 3. one correctly. 
I have another idea how to implement it using the callback, but that is a bit more work... so I would be happy if it is not needed.


Something else you could try is to change the "seed" byte here:
https://github.com/ColPaulR/GRBL-USB-CNC-Pendant/blob/master/src/Pendant_WHB04B6.h#L14
... to 0x04, like in your Node JS code:
https://github.com/ColPaulR/cncjs-pendant-XHC/blob/main/XHC-HB04.js#L30

Though according to the documentation from LinuxCNC, this might interfere with the checksum:
https://github.com/LinuxCNC/linuxcnc/tree/master/src/hal/user_comps/xhc-whb04b-6#checksum-investigation
Checking is done here, if you need to remove it:
https://github.com/ColPaulR/GRBL-USB-CNC-Pendant/blob/master/src/Pendant_WHB04B6.cpp#L43-L45

**Comment by hurzhurz** [comment]
Did you already have the chance to do further testing?
Especially if the newer one works with NodeJS/Col1 or if the "seed" byte makes a difference would be interesting.

Another thing I'm curious about:
In the HID reports you receive from the pendants, is the second byte fixed (and identical for all) or does it change?
The [LinuxCNC doc](https://github.com/LinuxCNC/linuxcnc/tree/master/src/hal/user_comps/xhc-whb04b-6#received-data-structure) says it is "random".
But on my WHB04B-6 the value never changes, which also limits my abilities to investigate the "checksum" calculation.

**Comment by ColPaulR** [comment]
I've gotten sidetracked with family and investigation some contention between FluidNC and CNC3D Commander. I'll take a look tomrrow if changing the seed in NodeJS makes a difference between the two pendants I have, as well as look at random byte from the pendants.

**Comment by ColPaulR** [comment]
I'm not seeing any change in the SEED value (buf[2]) with the old/wired controller and NodeJS. I tried 0x04, 0x00, 0x80, 0xFE & 0xFF. There was no effect that I could tell on the output of the display. I powered off (using pendant power button) between each try. 

I was able to export the USB traffic to an HTML file, which is attached as [USB Log.htm.zip](https://github.com/hurzhurz/Duet-USB-CNC-Pendant/files/14352784/USB.Log.htm.zip). Packet #169 appears to be where NodeJS starts to opens the file handles. From what I saw, that happens fours times (169-176). Packeet #177 is the 1st 8 bytes of the control message to the LCD. This is where I was playing around with the SEED value (currently 0x08 in the usb bus traffic).

The LCD values were X=2.3450 Y=3.4560 Z=1.2340 with a raw buffers of 
06fefd080002007a
060d0300d0110100
0624090000000000  

The software logged all of the 8 byte reports from the pendant. The random (byte 1) byte was always zero. In NodeJS, I don't screen for the CRC or even look at the random byte.

**Comment by hurzhurz** [comment]
I don't know how the power button works on the wired version, but on the wireless one, I have to unplug/replug the USB dongle if I want to be sure as the dongle seems to buffer the display data.
Can you still see the pendant in the device manager etc when it is powered off? If yes, you probably need to unplug it, too.
So maybe still a small chance changing the "seed" byte helps? :)

Thanks for the log, though I doesn't seem to give any helpful clue... looks like expected I guess.

Have you also yet tested how the different pendant version react to Col1 vs. Col2?

Well and I will give it another try to send the report in 8-byte-packets instead of all 24 bytes at once.

The "random" byte is strange. In my case it is always 0x10. But the examples from the LinuxCNC actually show changing values.
I think checking the CRC is generally a good idea to avoid bougs inputs, but if the calculation doesn't work in some cases (e.g. different seed byte needed), it is probably ok to ignore it.

**Comment by hurzhurz** [comment]
ok, got it working with 8-byte-packets. would you test it?:
https://github.com/hurzhurz/Duet-USB-CNC-Pendant/tree/reporttest
I have enabled the demo-axis-data, so you can simply use the compiled firmware.uf2 for testing

**Comment by ColPaulR** [comment]
Will do. I'll also check the Col1 vs Col2 with the USB monitor and see what the seed is with the wireless. Wired Pendant resets the screen to some strange numbers when powered off and then on, so I have confidence that the update is happening despite a seed change, at least with the values I tried.

**Comment by ColPaulR** [comment]
I just tried Col1 vs Col2 in NodeJS. I can only read from Col1 and write to Col2. Trying to read from Col2 produces an exceptions, as does trying to write to Col1. https://github.com/ColPaulR/cncjs-pendant-XHC/blob/main/XHC-HB04-test.js strips out all the CNCjs stuff and is just pure NodeJS if you want to try. I print the string path to the 2 devices that x64 finds as HID devices and then print the "found" message and the three 8-byte report hex values. The program sends these hex values and then listens for keypresses. Below is the stdout:

> \\?\HID#VID_10CE&PID_EB93&Col01#7&2a6ce7d5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
>\\?\HID#VID_10CE&PID_EB93&Col02#7&2a6ce7d5&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
>found XHC-HB04 device
>06fefd080002007a
>060d0300d0110100
>0624090000000000

This works with the new and the old (wireless and wired) pendant. Attached is the low level USB capture of the wireless/new Pendant with the above code. The only differences I can see are that the wireless does not ask for the USB device descriptor strings. I'm assuming that the wireless does that when the dongle is first inserted and before I start spying on the USB message traffic.

[Wireless Pendant.html.zip](https://github.com/hurzhurz/Duet-USB-CNC-Pendant/files/14367514/Wireless.Pendant.html.zip)

**Comment by ColPaulR** [comment]
I just downloaded and tested your remotetest branch. That worked for my old/wired controller, as well as the new/wireless one!

Interesting behavior thought. When I unplug the usb between the two pendants, I get the expected "HID device address = 1, instance = 0 no more mounted" message. However, the pico will not detect the other device being plugged in. If I disconnect and then reconnect the new/wireless usb dongle, the pico will not detect the new device. However, if I disconnect/reconnect the old wireless, it remounts the device. Same behavior if I use the power button the old/wireless.

Small issues with something in main1.cpp I'm guess, but HUGE success on getting both pendants to work! Are you going to merge the reporttest branch back into your master branch? I've made some edits/adds to your files and will merge three 8-byte reports back into mine once you consider them stable/baseline. Thanks SO MUCH for working this with/for me!

BTW, I don't know if you saw in the prior post attachment, but my wireless/new pendant had a 0x10 for the random byte.

**Comment by hurzhurz** [comment]
Great that it's working now, thanks for all the testing!
I will probably do some small changes and then indeed merge it into the master branch. It's good to have an increase compatibility.

While we now know that Col1/2 wasn't the issue, it is still interesting to know.

The unmount behavior is a bit strange. I'm not sure if there can be done much in main1.cpp.
The "no more mounted" message comes from the "check_devices_still_mounted" function where I check the mount status with tuh_hid_mounted().
But normally this shouldn't be necessary as there is also a callback "tuh_hid_umount_cb", which unfortunately doesn't work reliable.
Maybe that belongs to the same issue that I have with Adafruit TinyUSB versions higher then 1.18.4. Newer versions don't seem to work with PlatformIO, but work fine with ArduinoIDE.
